### ISSUE TITLE
OAuth 2.1 Support/Roadmap

### ISSUE THREAD

**Issue by metacubed** [spring-projects-experimental/spring-authorization-server#200]
Which features from OAuth 2.1 will be supported by Spring Authorization Server? Is there a roadmap or any documentation on this topic?

For example:
- [ ] PKCE support
- [ ] Remove implicit grant
- [ ] Remove password grant
- [ ] Remove query-based bearer tokens
- [ ] Constraints on refresh tokens
- [ ] Redirect URI enforcement changes

**Comment by jgrandja** [comment]
@metacubed Spring Authorization Server is aligning with OAuth 2.1.

> Is there a roadmap or any documentation on this topic?

See [Feature Planning](https://github.com/spring-projects-experimental/spring-authorization-server#feature-planning) section and [Feature List](https://github.com/spring-projects-experimental/spring-authorization-server/wiki/Feature-List) wiki. **NOTE:** I literally started the feature list page yesterday so it's a WIP. I'm planning on detailing it more by end of week.

**Comment by dfcoffin** [comment]
Is it possible to use the ZenHub "RoadMap" feature to be able to have an idea of when features are planned to be implemented?

**Comment by jgrandja** [comment]
@dfcoffin When this project started I did use the Roadmap feature but quickly found it extra overhead from a project management standpoint. Mainly because priorities change quite a bit and I need to shuffle things around. The Roadmap feature requires dates and therefore is too constrictive from an agile methodology process.

The project board has been working well. Features are prioritized in order from top to bottom in each pipeline. Features are scheduled from Icebox (longer term) and moved to Backlog (short term / next release) and eventually to In-progress which at that point will be assigned a Milestone release.

**Comment by dfcoffin** [comment]
@jgrandja Thanks for the explanation.  Since this is a community project, I understand that planning is challenging, given the inability to control when submissions will be provided and the effort to ensure they provide the proper support and meet the documentation and naming standards.

Is it possible to indicate in the new "Features" list the release targeted for the feature?  Are you now trying to make monthly releases?

Thanks for herding the cats on this project.

**Comment by jgrandja** [comment]
@dfcoffin 

> Is it possible to indicate in the new "Features" list the release targeted for the feature?

I think what makes the most sense is to assign the open issue a milestone release instead. So over the next 1-2 weeks I will go through all issues in the Icebox / Backlog and assign a release. But keep in mind that it may change as priorities shift. But at least this will give you an idea on when to expect a feature to be released. Does this work?

> Are you now trying to make monthly releases?

After I get `0.1.0` out (delayed to Feb 11), I do plan on doing more frequent releases. Ideally once a month but not more than 2 months. It depends how things go. I would like to have at least 2 major features per release.

**Comment by dfcoffin** [comment]
@jgrandja 

> I think what makes the most sense is to assign the open issue a milestone release instead. So over the next 1-2 weeks I will go through all issues in the Icebox / Backlog and assign a release. But keep in mind that it may change as priorities shift. But at least this will give you an idea on when to expect a feature to be released. Does this work?

Yes, that will definitely help, especially if the Icebox/Backlog can be sorted in the release sequence.

**Comment by jgrandja** [comment]
@dfcoffin Ok. I will target to have release milestones assigned by next Friday.
